### ISSUE TITLE
Maybe, position should use relative layout?

### ISSUE THREAD

**Issue by vastpeng** [sqshq/sampler#15]
same postion(`[[0, 38], [80, 2]]`) but different display.
![image](https://user-images.githubusercontent.com/15377472/62421510-5f9e2600-b6d5-11e9-8e43-08c1ea13ca2f.png)
![image](https://user-images.githubusercontent.com/15377472/62421512-6462da00-b6d5-11e9-80bf-1293db2d62c9.png)

**Comment by sqshq** [comment]
Hi @vastpeng,
Position and size of a component are relative to the terminal size.
`[[0, 38], [80, 2]]` - this array specifies coordinates on a relative grid (the whole screen = 80x40)

The problem with that - it is not very precize in the terminal. Because of the rounding, you might experience a slight diferent proportions when you resize the window, or zoom it.

I already tried to tune it to have the better results, so can't provide any fix for now. The recommendation is to move/resize a component if you changed the window size/zoom and it started to look weird.

And as always, if you figure out a way to do better rendering for this cases - contributions are very welcome. Thank you.
