### ISSUE TITLE
LICENSE sucks. Please choose something described as 'free software' by the FSF.

### ISSUE THREAD

**Issue by cogburnd02** [sqshq/sampler#6]
The FSF describes many licenses as free software. Please choose one of them for this project.

https://www.gnu.org/philosophy/shouldbefree.en.html

https://www.gnu.org/licenses/license-list.en.html

**Comment by cogburnd02** [comment]
Comments on reddit: https://old.reddit.com/r/linux/comments/clfxel/visualization_for_any_shell_command_right_from/

**Comment by alexejk** [comment]
Horrible license. This is not a free software license neither is it open-source license.
I would want to use this and most likely even contribute, but will not even bother because of the choice of license.
Please consider changing to any other widely used and accepted license.

**Comment by sqshq** [comment]
Exactly. The software [is not free for commercial use](https://sampler.dev/#pricing) at the moment. 

The [Fair Source License](https://fair.io) allows me to share the code with the community, distribute it for free in case of personal usage and provide a paid license for companies.

**Comment by cogburnd02** [comment]
Techrepublic author [Matt Asay called the "Fair Source" license "the worst thing to happen to open source".](https://www.techrepublic.com/article/fair-source-licensing-is-the-worst-thing-to-happen-to-open-source-definitely-maybe/) He's absolutely right.

He also says "Go open or go closed, but don't confuse developers with a Milquetoast version of open source." I completely agree.

He closes with this paragraph, with which I (and I daresay, most free-software/open-source developers) completely agree:

"So, Fair Source advocates...give it up. It's the wrong way to treat developers, and it's the wrong way to treat yourselves. Fair Source is an attempt to resurrect yesterday's software licensing model in a world that has gone open source and cloud. Time to move on."

Additionally, since the LICENSE is the same as it was when this bug was opened, the bug Should Not Have Been Closed. The bug [License sucks] still exists, and will continue to exist until you change the License.

Ignoring a bug doesn't make it go away.

**Comment by anko** [comment]
@cogburnd02  Please drop the hostile tone.  It hinders the cause.  If someone doesn't believe what you do, ask questions, try to understand their viewpoint, and present your reasoning.

- - -

@sqshq I'm having difficulty understanding what would violate the "1 user" restriction for this type of software.  For example,

 - If all of my coworkers download a copy, they each get a "1 user" license, so presumably they can all run it on their individual machines?  If one of them then starts the software on a shared shell on a server that multiple people could log in to, is that shared access a violation of the license, even though all of them would be allowed to start an exactly equivalent instance of it individually?

 - If I render the output of the visualisation on a screen in the office hallway, and 10 people walk past it, are those 10 people "users", or is it a private performance in which the software was only used by me to produce that performance?

What are some examples of situations where I'd have to buy a license?

Also, the license text doesn't restrict commercial use, but the [pricing page](https://sampler.dev/#pricing) implies otherwise, with "free for non-commercial use".  Is this an oversight?

**Comment by cogburnd02** [comment]
@anko [I don't get randomly hostile. I get hostile when hostility is called for.](https://www.youtube.com/watch?v=bVKUiqDcGm4)

Having proprietary software masquerading as "Fair" and "shared" when it is demonstrably (and fairly obviously) unfair and 'shared' only with some but not all strongly calls for hostility that I'm only too happy to provide.

> try to understand their viewpoint

This is a bit like asking me to 'understand the viewpoint' of an anti-vaxxer or a flat-earther. It may very well be their viewpoint, but it's also absolutely wrong, and deserves to be called out as such.

**Comment by sqshq** [comment]
Hi @anko,
The [license website](https://fair.io) has a bunch of answers and examples, e.g.

> Can I use Fair Source software for myself or my friends and family?
> Yes. As an individual, you can use the software all you want for your own personal use. The Use Limitation will only apply if you use the software for the benefit of a company.
> 

> Can I use Fair Source software inside my company?
> Yes. You must pay a license fee if your organization has more people using the software than the specified Use Limitation. For example, let’s say the software is licensed as Fair Source 25 (i.e., the Use Limitation is 25 users). If less than 25 people use the software within your company, the software is free. If 25 or more people use the software, your company must pay a license fee to use the software.

So in our case, 1 person in a company can use the software for free.

Pricing page has two options - donation for non-commercial usage, and a purchase of a license - for commercial. I'm not saying anything about restrictions there, because it is a part of full License agreement (link to that page is just above those options)

Since it is not very obvious, let me add a link to fair.io Q/A on the website.

**Comment by VegaDeftwing** [comment]
Adding my 2cents:
Do I like the license: no
Do I think a 1-user licence is sensible: no
Is it in any way my choice: no
Should we harass the dev to get it changed: no
Should you not use this software because you disagree with the license: that's up to you

Ultimately I don't really forsee this project, as interesting as it is, being used by many outside of the r/unixporn community, much less by businesses. I do, however, recognize that the developer does deserve to chose the license for his/her work and that any dev needs money to live- and the choice in licence impacts this. Ideally we, as an open source community, would support the project to the point that there's no need to charge for commercial use, but (with a few exceptions) most linux users are cheap and projects like this will receive between $0 and "eaten by transaction fees" in donations.

If you really hate the project you could always clean room re-impliment it. But nobody has any right to act the way some here and on reddit have. We, as a community, need to be better than that.

**Comment by anko** [comment]
@sqshq 

>> The Use Limitation will only apply if you use the software for the benefit of a company.

>> You must pay a license fee if your organization has more people using the software than the specified Use Limitation.

I see.

I would have expected the entirety of the license terms to be contained in the license text, at [`/LICENSE`](https://github.com/sqshq/sampler/blob/0a88bd37270b88221ddb9fbe7f6589bc3ba02bfe/LICENSE), but it does not mention these things.  Would it be possible to amend the license text to state all of the actually intended terms?  I'd rather not worry about whether there's some other FAQ document by the license authors that I've missed, which might also be offline 5 years from now.

**Comment by Spazturtle** [comment]
@sqshq 
> So in our case, 1 person in a company can use the software for free.

This is a poorly written licence that is simply not workable and wouldn't hold up in court if you tried to enforce the use limitation section. There is a reason people and companies tend to stick to tried and tested licences.


@anko 
>I would have expected the entirety of the license terms to be contained in the license text, at /LICENSE, but it does not mention these things. Would it be possible to amend the license text to state all of the actually intended terms? I'd rather not worry about whether there's some other FAQ document by the license authors that I've missed, which might also be offline 5 years from now.

The only terms of the licence are the ones in the licence document, what is written on other sites doesn't is irrelevant, if the dev wanted them to be part of the licence then he should have included them in the licence.

**Comment by sqshq** [comment]
@Spazturtle 😂 thank you for the legal advice
consider to read a [review of this license](https://writing.kemitchell.com/2016/03/30/First-Read-of-the-Fair-Source-License.html) from someone who knows what he's talking about.
